name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10, 12, 14]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }} @ ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run compile

    - name: Run tests
      run: npm test
